[plugin]
# for this, you should install piper yazi plugin. Run
# ya pkg add yazi-rs/plugins:piper
# and install bat
# brew install bat
prepend_previewers = [
  { url = "*/",  run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },

  { url = "*.py",  run = 'piper -- bat -p --theme="Nord" --color=always "$1"' },
  { url = "*.lua", run = 'piper -- bat -p --theme="kanagawa-dragon" --color=always "$1"' },
  { url = "*.tex", run = 'piper -- bat -p --theme="kanagawa-dragon" --color=always "$1"' },
  { url = "*.toml", run = 'piper -- bat -p --theme="kanagawa" --color=always "$1"' },
  { url = "*.fish", run = 'piper -- bat -p --theme="kanagawa-dragon" --color=always "$1"' },
]
